os: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules

branches:
  only:
    - master

install:
  - ps: Install-Product node 10 x64
  - yarn install --force

build_script:
  - yarn check-prettier
  - yarn build
  - ./script/test-appveyor.bat
  - yarn prebuild-node
  - yarn prebuild-node-ia32
  - yarn prebuild-electron
  - yarn prebuild-electron-ia32
  - if defined APPVEYOR_REPO_TAG_NAME (npm run upload)

test: off
deploy: off
